### ISSUE TITLE
it seems that the script is encountering an exception and failing to execute.

### ISSUE THREAD

**Issue by biliboomboom** [owenwijaya22/qobuz#2]
Logging...
Logged: OK
Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "qobuz_dl\core.py", line 73, in initialize_client
  File "qobuz_dl\qopy.py", line 39, in __init__
  File "qobuz_dl\qopy.py", line 126, in auth
qobuz_dl.exceptions.IneligibleError: Free accounts are not eligible to download tracks.
[7604] Failed to execute script 'main' due to unhandled exception!

**Comment by v-owen** [comment]
haha sorry for the late reply, yes it's fixed now!

**Comment by WFFWJH** [comment]
> haha sorry for the late reply, yes it's fixed now!

Hello, this software doesn't seem to work again, the error log I can't provide because I can't pause the console. I don't know if it's my own reason, can you still use it？
